// vue-graphql/src/components/add-author.vue
<template>
  <div class="container">
    <form class="form-horizontal">
      <div class="form-group">
        <label for="author" class="col-sm-2 control-label">作者</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="author" placeholder="请输入作者" v-model="name">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="button" class="btn btn-default" @click="subForm">提交</button>
        </div>
      </div>
    </form>
  </div>
</template>

<script>
  export default {
    data() {
      return{
        name: ''
      }
    },
    methods: {
      subForm() {
        console.log(this.name)
        if( this.name ) {
          this.$graphql.request(`
            mutation{
              createAuthor(name:"${this.name}"){
                status
              }
            }
          `).then(result => {
            if(result.createAuthor.status == 200 ) {
              this.$router.push({
                path: '/'
              });
            }
          })
        }
      }
    }
  }
</script>

<style scoped>

</style>

// react-graphql/src/views/add-author.jsx
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { withApollo } from 'react-apollo';
import { gql } from 'apollo-boost';

class AddAuthor extends Component {
  subForm() {
    let author = ReactDOM.findDOMNode(this.refs['input']).value;
    if (author) {
      const mutationSQL = gql`
        mutation createAuthor($name: String!){
          createAuthor(name: $name) {
            status
          }
        }
      `;
      this.props.client.mutate({ mutation: mutationSQL, variables: {name: author} }).then(({data: {createAuthor: { status }}}) => {
        if (status === 200) {
          // 回到首页
          this.props.history.push('/');
        }
      });
    }
  }
  render() {
    return (
      <div className="container">
        <form className="form-horizontal">
          <div className="form-group">
            <label htmlFor="author" className="col-sm-2 control-label">作者</label>
            <div className="col-sm-10">
              <input type="text" className="form-control" id="author" ref="input" placeholder="请输入作者"/>
            </div>
          </div>
          <div className="form-group">
            <div className="col-sm-offset-2 col-sm-10">
              <button type="button" className="btn btn-default" onClick={() => this.subForm()}>提交</button>
            </div>
          </div>
        </form>
      </div>
    )
  }
}

export default withApollo(AddAuthor);
