// react-graphql/src/views/add-book.jsx
import React, { Component } from 'react';
import { withApollo } from 'react-apollo';
import { gql } from 'apollo-boost';
class AddBook extends Component {
  constructor(props) {
    super(props);
    this.state = {
      postData: {
        book: '',
        price: '',
        category: 1,
        author: 1
      },
      categoryList: [],
      authorList: []
    };
  }
  changeBook(event) {
    this.setState({ postData: Object.assign(this.state.postData, { book: event.target.value }) });
  }
  changePrice(event) {
    this.setState({ postData: Object.assign(this.state.postData, { price: event.target.value }) });
  }
  changeCategory(event) {
    this.setState({ postData: Object.assign(this.state.postData, { category: event.target.value }) });
  }
  changeAuthor(event) {
    this.setState({ postData: Object.assign(this.state.postData, { author: event.target.value }) });
  }
  // 提交数据到后台
  subForm() {
    const {book, price, category, author} = this.state.postData;
    const mutationSQL = gql`
      mutation createBook($name: String!, $price: Float, $category: Int!, $author: Int!){
        createBook(bookData: {name: $name, price: $price, category: $category, author: $author}){
          status
        }
      }
    `;
    this.props.client.mutate({ mutation: mutationSQL, variables: {name: book, price: price, category: category, author: author} }).then(({data: {createBook: { status }}}) => {
      if (status === 200) {
        // 回到首页
        this.props.history.push('/');
      }
    });
  }
  componentDidMount() {
    const querySQL = gql`
      query{
        allAuthor{
          id,
          name
        },
        allCategory{
          id,
          name
        }
      }
    `;
    this.props.client.query({ query: querySQL }).then(({ data: { allAuthor, allCategory } }) => {
      this.setState({ authorList: allAuthor, categoryList: allCategory });
    });
  }
  render() {
    const { postData, categoryList, authorList } = this.state;
    return (
      <div className="container">
        <form className="form-horizontal">
          <div className="form-group">
            <label htmlFor="book" className="col-sm-2 control-label">书籍</label>
            <div className="col-sm-10">
              <input type="text" className="form-control" id="book" placeholder="请输入书名" value={postData.book} onChange={(event) => this.changeBook(event)} />
            </div>
          </div>
          <div className="form-group">
            <label htmlFor="price" className="col-sm-2 control-label">价格</label>
            <div className="col-sm-10">
              <input type="text" className="form-control" id="price" placeholder="请输入价格" value={postData.price} onChange={(event) => this.changePrice(event)} />
            </div>
          </div>
          <div className="form-group">
            <label htmlFor="category" className="col-sm-2 control-label">分类</label>
            <div className="col-sm-10">
              <select className="form-control" value={postData.category} onChange={(event) => this.changeCategory(event)}>
                {
                  categoryList.map((item, index) => {
                    return <option value={item.id} key={index}>{item.name}</option>
                  })
                }
              </select>
            </div>
          </div>
          <div className="form-group">
            <label htmlFor="author" className="col-sm-2 control-label">作者</label>
            <div className="col-sm-10">
              <select className="form-control" value={postData.author} onChange={(event) => this.changeAuthor(event)}>
                {
                  authorList.map((item, index) => {
                    return <option value={item.id} key={index}>{item.name}</option>
                  })
                }
              </select>
            </div>
          </div>
          <div className="form-group">
            <div className="col-sm-offset-2 col-sm-10">
              <button type="button" className="btn btn-default" onClick={() => this.subForm()}>提交</button>
            </div>
          </div>
        </form>
      </div>
    )
  }
}

export default withApollo(AddBook);

// vue-graphql/src/components/add-book.vue
<template>
  <div class="container">
    <form class="form-horizontal">
      <div class="form-group">
        <label for="book" class="col-sm-2 control-label">书籍</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="book" placeholder="请输入书名" v-model="formData.name">
        </div>
      </div>
      <div class="form-group">
        <label for="price" class="col-sm-2 control-label">价格</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="price" placeholder="请输入价格" v-model="formData.price">
        </div>
      </div>
      <div class="form-group">
        <label for="category" class="col-sm-2 control-label">分类</label>
        <div class="col-sm-10">
          <select class="form-control" v-model="formData.category">
            <template v-if="category.length > 0" v-for="item of category">
              <option :value="item.id">{{item.name}}</option>
            </template>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label for="author" class="col-sm-2 control-label">作者</label>
        <div class="col-sm-10">
          <select class="form-control" v-model="formData.author">
            <template v-if="author.length > 0" v-for="item of author">
              <option :value="item.id">{{item.name}}</option>
            </template>
          </select>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="button" class="btn btn-default" @click="subForm">提交</button>
        </div>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  data(){
    return{
      author: [],
      category: [],
      formData: {
        name:'',
        price:'',
        category:'',
        author:''
      }
    }
  },
  mounted(){
    this.getAllCategory();
    this.getAllAuthor();
  },
  methods: {
    getAllCategory() {
      this.$graphql.request(`
          query{
            allCategory{
              id,
              name
            }
          }
        `).then(result => {
          this.category = result.allCategory;
      })
    },
    getAllAuthor() {
      this.$graphql.request(`
          query{
            allAuthor{
              id,
              name
            }
          }
        `).then(result => {
          this.author = result.allAuthor;
          // console.log(result);
      })
    },
    subForm(){
      console.log(this.formData)
      if(this.formData.name && this.formData.price && this.formData.category && this.formData.author) {
        this.$graphql.request(`
          mutation{
            createBook(bookData:{name:"${this.formData.name}",price:${this.formData.price},category:${this.formData.category},author:${this.formData.author}}){
              status
            }
          }
        `).then(result => {
          console.log(result);
          if(result.createBook.status == 200) {
            this.$router.push({
              path: '/'
            });
          }
        })
      }
    }
  }
};
</script>

<style scoped>

</style>
